package:
  name: SPIT
  version: 0.1

source:
  path: ../dist

requirements:
  build:
    - python
  run:
    - python >=3.9
    - r-base >=4.0
    - matplotlib >=3.4.3
    - matplotlib_venn >=0.11.6
    - numpy >=1.20.3
    - pandas >=1.3.4
    - rpy2 >=3.5.14
    - scikit_learn >=1.1.1
    - scipy >=1.11.3
    - seaborn >=0.11.2
    - tqdm >=4.62.3

test:
  imports:
    - SPIT

about:
  home: https://github.com/berilerdogdu/SPIT
  license: GPL-3.0-or-later
  summary: Differential transcript usage analysis tool

extra:
  recipe-maintainers:
    - Beril Erdogdu (berdogd1@jhu.edu)
